name: example-client-payload-action
on: repository_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_DEV_ID }}
          service_account_key: ${{ secrets.GCP_PROJECT_SA_KEY }}
          export_default_credentials: true     
      - name: Deploy to dev
        if: github.event.client_payload.ref == 'staging'
        run: gcloud compute ssh --zone "us-central1-a" "base-image" --project "joyride-gcp-dev-env" --quiet
             --command="sudo rm -rf /tmp/joyride && sudo git clone -b ${{toJson(github.event.client_payload.ref)}} https://github.com/joyridedev/test.git /tmp/joyride/ && sudo cp -r /tmp/joyride/* /var/www/html/"

notify:

    name: Notify on Slack
    runs-on: ubuntu-latest
    # Only run this workflow when "build" workflow succeeds
    needs: [build-deploy]

    # Only run this workflow if it target is main branch on pull_request event
    #if: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' }}

    steps:

      - uses: rtCamp/action-slack-notify@v2
        env:
          # required
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Contributor :* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}' 
        
        # Pick up events even if the job is success.
        if: success()
