name: example-client-payload-action
on: repository_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_DEV_ID }}
          service_account_key: ${{ secrets.GCP_PROJECT_SA_KEY }}
          export_default_credentials: true     
      - name: Deploy to dev
        if: github.event.client_payload.ref == 'staging'
        run: gcloud compute ssh --zone "us-central1-a" "base-image" --project "joyride-gcp-dev-env" --quiet
             --command="sudo rm -rf /tmp/joyride && sudo git clone -b ${{toJson(github.event.client_payload.ref)}} https://github.com/joyridedev/test.git /tmp/joyride/ && sudo cp -r /tmp/joyride/* /var/www/html/"
   
  notify:
     needs: [build-deploy]
     name: Slack Notification
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Slack Notification
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
         SLACK_USERNAME: Deployment-service
         SLACK_ICON: https://joyride.city/wp-content/uploads/2019/11/joyride-logo.png?size=48
         SLACK_FOOTER: Powered By Joyride's GitHub Actions Library
         SLACK_TITLE: Notification
         SLACK_MESSAGE: ${{toJson(github.event.head_commit.message)}}  Deployed
       if: success()
