name: example-client-payload-action
on: repository_dispatch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_DEV_ID }}
          service_account_key: ${{ secrets.GCP_PROJECT_SA_KEY }}
          export_default_credentials: true     
      - name: Deploy to dev
        if: github.event.client_payload.ref == 'staging'
        run: gcloud compute ssh --zone "us-central1-a" "base-image" --project "joyride-gcp-dev-env" --quiet
             --command="sudo rm -rf /tmp/joyride && sudo git clone -b ${{toJson(github.event.client_payload.ref)}} https://github.com/joyridedev/test.git /tmp/joyride/ && sudo cp -r /tmp/joyride/* /var/www/html/"

  notify:
      name: Notify on Slack
      runs-on: ubuntu-latest
      needs: [build-deploy]
      steps:
          - uses: 8398a7/action-slack@v3
            env:
               SLACK_COLOR: ${{ job.status }}
               SLACK_TITLE: Post Title
               SLACK_MESSAGE: 'Post Content :rocket:'
               SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            if: always()
